/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project_LendMe;

import javax.swing.JLayeredPane;
import javax.swing.JPanel;



/**
 *
 * @author Anja, Katharina
 */
public class GUI extends javax.swing.JFrame implements Runnable {
    
    private final DatabaseHelper hp = new DatabaseHelper();
    
  
    /**
    * Creates new form GUI
    */
    public GUI() {
        
        initComponents();
        System.out.println("lululu " + return_panel.getComponentZOrder(re_userName));
       
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        toppenal = new javax.swing.JPanel();
        parentpanel = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        newrental = new javax.swing.JButton();
        rentallist = new javax.swing.JButton();
        archive = new javax.swing.JButton();
        inventory = new javax.swing.JButton();
        startpage = new javax.swing.JPanel();
        scrollpane_startpage = new javax.swing.JScrollPane();
        layerpane = new javax.swing.JLayeredPane();
        home_panel = new javax.swing.JPanel();
        newrental_panel = new javax.swing.JPanel();
        newrentaltitle = new javax.swing.JLabel();
        devicename = new javax.swing.JLabel();
        manufacturername = new javax.swing.JLabel();
        inventory_number = new javax.swing.JLabel();
        rentedby = new javax.swing.JLabel();
        rentTo = new javax.swing.JLabel();
        productname_newrental = new javax.swing.JComboBox<>();
        manufacturer_newrental = new javax.swing.JComboBox<>();
        inventorynumber_newrental = new javax.swing.JComboBox<>();
        userID_newrental = new javax.swing.JComboBox<>();
        userFirstName = new javax.swing.JTextField();
        userLastName = new javax.swing.JTextField();
        userEmail = new javax.swing.JTextField();
        userPhone = new javax.swing.JTextField();
        year_newrental = new javax.swing.JComboBox<>();
        administrator_newrental = new javax.swing.JComboBox<>();
        date = new javax.swing.JLabel();
        rentalDate_newrental = new com.raven.datechooser.DateChooser();
        adminFullName = new javax.swing.JTextField();
        save_newrental = new javax.swing.JButton();
        cancel_newrental = new javax.swing.JButton();
        rentallist_panel = new javax.swing.JPanel();
        rentallist_title = new javax.swing.JLabel();
        searchfilter_rentallist = new javax.swing.JComboBox<>();
        filter_options_rentallist = new javax.swing.JLabel();
        return_button = new javax.swing.JButton();
        filterString_rentallist = new javax.swing.JLabel();
        filterText_rentallist = new javax.swing.JTextField();
        asc_rentallist = new javax.swing.JRadioButton();
        desc_rentallist = new javax.swing.JRadioButton();
        filterbutton_rentallist = new javax.swing.JButton();
        btClear_rentals = new javax.swing.JButton();
        rental_ScrollPane = new javax.swing.JScrollPane();
        rentallist_table = new javax.swing.JTable();
        inventory_panel = new javax.swing.JPanel();
        newdevice_button = new javax.swing.JButton();
        inventory_title = new javax.swing.JLabel();
        searchfilter_inventory = new javax.swing.JComboBox<>();
        filter_options_inventory = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        inventory_table = new javax.swing.JTable();
        return_panel = new javax.swing.JPanel();
        re_notes = new javax.swing.JTextArea();
        productname_return = new javax.swing.JLabel();
        re_productname = new javax.swing.JTextField();
        return_title = new javax.swing.JLabel();
        returndate = new com.raven.datechooser.DateChooser();
        yes = new javax.swing.JRadioButton();
        re_manufacturer = new javax.swing.JTextField();
        re_inventroyNumber = new javax.swing.JTextField();
        re_UserID = new javax.swing.JTextField();
        manufacturer_return = new javax.swing.JLabel();
        userID_return = new javax.swing.JLabel();
        inventorynumber_return = new javax.swing.JLabel();
        returnDate_return = new javax.swing.JLabel();
        notes_return = new javax.swing.JLabel();
        factorysettings_return = new javax.swing.JLabel();
        userName_return = new javax.swing.JLabel();
        userPhone_return = new javax.swing.JLabel();
        userMail_return = new javax.swing.JLabel();
        re_userName = new javax.swing.JTextField();
        re_userPhone = new javax.swing.JTextField();
        re_userMail = new javax.swing.JTextField();
        save_return = new javax.swing.JButton();
        cancel_return = new javax.swing.JButton();
        newdevice_panel = new javax.swing.JPanel();
        newdevice_title = new javax.swing.JLabel();
        devicename_newdevice = new javax.swing.JLabel();
        manufacturer_newdevice = new javax.swing.JLabel();
        inventorynumber_newdevice = new javax.swing.JLabel();
        IMEInumber_newdevice = new javax.swing.JLabel();
        acquisitiondate_newdevice = new javax.swing.JLabel();
        acquisitionDate = new com.raven.datechooser.DateChooser();
        save_newdevice = new javax.swing.JToggleButton();
        cancel_newdevice = new javax.swing.JToggleButton();
        manufacturer = new javax.swing.JTextField();
        productname = new javax.swing.JTextField();
        inventoryNumber = new javax.swing.JTextField();
        imei = new javax.swing.JTextField();
        room_newdevice = new javax.swing.JLabel();
        location = new javax.swing.JTextField();
        notes_newdevice = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        administrator_newdevice = new javax.swing.JLabel();
        administrator = new javax.swing.JComboBox<>();
        acquisitionvalue_newdevice = new javax.swing.JLabel();
        acquisitionValue = new javax.swing.JTextField();
        archive_panel = new javax.swing.JPanel();
        archive_title = new javax.swing.JLabel();
        searchfilter_archive = new javax.swing.JComboBox<>();
        search_options_archive = new javax.swing.JLabel();
        filter_options_archive = new javax.swing.JLabel();
        filterText_archive = new javax.swing.JTextField();
        asc_archive = new javax.swing.JRadioButton();
        desc_archive = new javax.swing.JRadioButton();
        filterButton_archive = new javax.swing.JButton();
        btClear_archive = new javax.swing.JButton();
        archive_ScrollPane = new javax.swing.JScrollPane();
        archive_table = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(826, 878));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        toppenal.setBackground(new java.awt.Color(87, 121, 50));
        toppenal.setPreferredSize(new java.awt.Dimension(802, 110));

        javax.swing.GroupLayout toppenalLayout = new javax.swing.GroupLayout(toppenal);
        toppenal.setLayout(toppenalLayout);
        toppenalLayout.setHorizontalGroup(
            toppenalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        toppenalLayout.setVerticalGroup(
            toppenalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(toppenal, java.awt.BorderLayout.PAGE_START);

        parentpanel.setBackground(new java.awt.Color(255, 255, 255));
        parentpanel.setPreferredSize(new java.awt.Dimension(802, 800));
        parentpanel.setLayout(new java.awt.BorderLayout());

        sidepanel.setBackground(new java.awt.Color(87, 121, 50));
        sidepanel.setMinimumSize(new java.awt.Dimension(100, 500));
        sidepanel.setPreferredSize(new java.awt.Dimension(250, 300));
        sidepanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        newrental.setBackground(new java.awt.Color(55, 57, 58));
        newrental.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newrental.setForeground(new java.awt.Color(255, 255, 255));
        newrental.setText("Neuer Verleih");
        newrental.setBorderPainted(false);
        newrental.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newrental.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        newrental.setIconTextGap(15);
        newrental.setPreferredSize(new java.awt.Dimension(250, 70));
        newrental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newrentalActionPerformed(evt);
            }
        });
        sidepanel.add(newrental);
        newrental.getAccessibleContext().setAccessibleDescription("");

        rentallist.setBackground(new java.awt.Color(55, 57, 58));
        rentallist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rentallist.setForeground(new java.awt.Color(255, 255, 255));
        rentallist.setText("Verleihliste");
        rentallist.setBorderPainted(false);
        rentallist.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rentallist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rentallist.setIconTextGap(15);
        rentallist.setPreferredSize(new java.awt.Dimension(250, 70));
        rentallist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentallistActionPerformed(evt);
            }
        });
        sidepanel.add(rentallist);

        archive.setBackground(new java.awt.Color(55, 57, 58));
        archive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        archive.setForeground(new java.awt.Color(255, 255, 255));
        archive.setText("Archiv");
        archive.setToolTipText("");
        archive.setActionCommand("Verleihliste");
        archive.setBorderPainted(false);
        archive.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        archive.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        archive.setIconTextGap(15);
        archive.setPreferredSize(new java.awt.Dimension(250, 70));
        archive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archiveActionPerformed(evt);
            }
        });
        sidepanel.add(archive);

        inventory.setBackground(new java.awt.Color(55, 57, 58));
        inventory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventory.setForeground(new java.awt.Color(255, 255, 255));
        inventory.setText("Inventar");
        inventory.setToolTipText("");
        inventory.setActionCommand("Verleihliste");
        inventory.setBorderPainted(false);
        inventory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inventory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventory.setIconTextGap(15);
        inventory.setPreferredSize(new java.awt.Dimension(250, 70));
        inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryActionPerformed(evt);
            }
        });
        sidepanel.add(inventory);

        parentpanel.add(sidepanel, java.awt.BorderLayout.LINE_START);
        sidepanel.getAccessibleContext().setAccessibleName("");

        startpage.setBackground(new java.awt.Color(220, 229, 211));
        startpage.setPreferredSize(new java.awt.Dimension(576, 800));

        scrollpane_startpage.setBorder(null);
        scrollpane_startpage.setPreferredSize(new java.awt.Dimension(576, 800));

        layerpane.setLayout(new java.awt.CardLayout());

        home_panel.setBackground(new java.awt.Color(220, 229, 211));
        home_panel.setPreferredSize(new java.awt.Dimension(576, 800));

        javax.swing.GroupLayout home_panelLayout = new javax.swing.GroupLayout(home_panel);
        home_panel.setLayout(home_panelLayout);
        home_panelLayout.setHorizontalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        home_panelLayout.setVerticalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );

        layerpane.add(home_panel, "card9");

        newrental_panel.setBackground(new java.awt.Color(220, 229, 211));
        newrental_panel.setPreferredSize(new java.awt.Dimension(576, 800));

        newrentaltitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newrentaltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newrentaltitle.setText("Neuer Verleih");

        devicename.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        devicename.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        devicename.setText("Gerätename");

        manufacturername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manufacturername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        manufacturername.setText("Herstellerbezeichnung");

        inventory_number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inventory_number.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inventory_number.setText("Inventarnummer");

        rentedby.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rentedby.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rentedby.setText("Verliehen von");

        rentTo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rentTo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rentTo.setText("Verleihen an");

        productname_newrental.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productname_newrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", " " }));

        manufacturer_newrental.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manufacturer_newrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        inventorynumber_newrental.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inventorynumber_newrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        userID_newrental.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userID_newrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userID_newrental.setToolTipText("Matrikelnummer");

        userFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userFirstName.setText("Vorname");
        userFirstName.setToolTipText("Vorname");

        userLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userLastName.setText("Nachname");
        userLastName.setToolTipText("Nachname");

        userEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userEmail.setText("E-Mail");
        userEmail.setToolTipText("E-Mail");

        userPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userPhone.setText("Telefonnummer");
        userPhone.setToolTipText("Telefonnummer\n Bsp. 0660/111111");

        year_newrental.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        year_newrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jahrgang" }));

        administrator_newrental.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        administrator_newrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        administrator_newrental.setToolTipText("Admin-ID");

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date.setText("Datum");

        rentalDate_newrental.setForeground(new java.awt.Color(87, 121, 50));
        rentalDate_newrental.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        adminFullName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminFullName.setText("Vor- und Nachname");
        adminFullName.setToolTipText("");

        save_newrental.setText("Speichern");

        cancel_newrental.setText("Abbrechen");

        javax.swing.GroupLayout newrental_panelLayout = new javax.swing.GroupLayout(newrental_panel);
        newrental_panel.setLayout(newrental_panelLayout);
        newrental_panelLayout.setHorizontalGroup(
            newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newrental_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newrental_panelLayout.createSequentialGroup()
                        .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(manufacturername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(devicename, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inventory_number, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(rentTo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(newrental_panelLayout.createSequentialGroup()
                                .addComponent(userPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(year_newrental, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(userEmail)
                            .addComponent(userID_newrental, 0, 307, Short.MAX_VALUE)
                            .addGroup(newrental_panelLayout.createSequentialGroup()
                                .addComponent(userFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userLastName))
                            .addComponent(productname_newrental, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manufacturer_newrental, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inventorynumber_newrental, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(newrentaltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newrental_panelLayout.createSequentialGroup()
                        .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentedby, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(administrator_newrental, 0, 307, Short.MAX_VALUE)
                            .addComponent(rentalDate_newrental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminFullName)
                            .addGroup(newrental_panelLayout.createSequentialGroup()
                                .addComponent(save_newrental, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancel_newrental, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        newrental_panelLayout.setVerticalGroup(
            newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newrental_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(newrentaltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(devicename)
                    .addComponent(productname_newrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturername)
                    .addComponent(manufacturer_newrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventory_number)
                    .addComponent(inventorynumber_newrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentTo)
                    .addComponent(userID_newrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_newrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentedby)
                    .addComponent(administrator_newrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date)
                    .addComponent(rentalDate_newrental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(newrental_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_newrental)
                    .addComponent(save_newrental))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        layerpane.add(newrental_panel, "card2");

        rentallist_panel.setBackground(new java.awt.Color(220, 229, 211));
        rentallist_panel.setPreferredSize(new java.awt.Dimension(564, 800));

        rentallist_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rentallist_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rentallist_title.setText("Aktuell verliehen");
        rentallist_title.setMaximumSize(new java.awt.Dimension(43, 20));
        rentallist_title.setMinimumSize(new java.awt.Dimension(43, 20));
        rentallist_title.setPreferredSize(new java.awt.Dimension(43, 20));

        searchfilter_rentallist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchfilter_rentallist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchfilter_rentallist.setMaximumSize(new java.awt.Dimension(125, 30));

        filter_options_rentallist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filter_options_rentallist.setText("Filter- und Sortieroptionen:");

        return_button.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        return_button.setText("Geräterückgabe");
        return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_buttonActionPerformed(evt);
            }
        });

        filterString_rentallist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filterString_rentallist.setText("Filern nach:");

        filterText_rentallist.setToolTipText("Wert nach dem gefiltert werden soll");
        filterText_rentallist.setMaximumSize(new java.awt.Dimension(125, 30));
        filterText_rentallist.setMinimumSize(new java.awt.Dimension(70, 30));
        filterText_rentallist.setPreferredSize(new java.awt.Dimension(125, 30));

        asc_rentallist.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        asc_rentallist.setText("ASC");
        asc_rentallist.setMaximumSize(new java.awt.Dimension(55, 30));
        asc_rentallist.setMinimumSize(new java.awt.Dimension(55, 30));
        asc_rentallist.setPreferredSize(new java.awt.Dimension(55, 30));

        desc_rentallist.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        desc_rentallist.setText("DESC");
        desc_rentallist.setMaximumSize(new java.awt.Dimension(60, 30));
        desc_rentallist.setMinimumSize(new java.awt.Dimension(60, 30));
        desc_rentallist.setPreferredSize(new java.awt.Dimension(60, 30));

        filterbutton_rentallist.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        filterbutton_rentallist.setText("Filter anwenden");

        btClear_rentals.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btClear_rentals.setText("Clear");
        btClear_rentals.setMaximumSize(new java.awt.Dimension(60, 32));
        btClear_rentals.setMinimumSize(new java.awt.Dimension(55, 32));
        btClear_rentals.setPreferredSize(new java.awt.Dimension(55, 32));

        rental_ScrollPane.setBackground(new java.awt.Color(220, 229, 211));
        rental_ScrollPane.setPreferredSize(new java.awt.Dimension(453, 403));

        rentallist_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ));
        rentallist_table.setMinimumSize(new java.awt.Dimension(514, 64));
        rentallist_table.setPreferredSize(new java.awt.Dimension(514, 64));
        rental_ScrollPane.setViewportView(rentallist_table);

        javax.swing.GroupLayout rentallist_panelLayout = new javax.swing.GroupLayout(rentallist_panel);
        rentallist_panel.setLayout(rentallist_panelLayout);
        rentallist_panelLayout.setHorizontalGroup(
            rentallist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentallist_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(rentallist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(return_button)
                    .addComponent(rental_ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                    .addGroup(rentallist_panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(rentallist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(filter_options_rentallist)
                            .addComponent(filterString_rentallist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(rentallist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(filterText_rentallist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchfilter_rentallist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(rentallist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(rentallist_panelLayout.createSequentialGroup()
                                .addComponent(asc_rentallist, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(desc_rentallist, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filterbutton_rentallist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addComponent(btClear_rentals, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rentallist_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        rentallist_panelLayout.setVerticalGroup(
            rentallist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentallist_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rentallist_title, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(rentallist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentallist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchfilter_rentallist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(asc_rentallist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(desc_rentallist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filter_options_rentallist, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(rentallist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentallist_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filterbutton_rentallist, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btClear_rentals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filterText_rentallist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterString_rentallist, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(rental_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(return_button)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        layerpane.add(rentallist_panel, "card3");

        inventory_panel.setBackground(new java.awt.Color(220, 229, 211));
        inventory_panel.setPreferredSize(new java.awt.Dimension(576, 800));

        newdevice_button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newdevice_button.setText("Neues Device anlegen");

        inventory_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inventory_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventory_title.setText("Inventar");

        searchfilter_inventory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchfilter_inventory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filter_options_inventory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filter_options_inventory.setText("Filterungs- und Sortiermöglichkeiten:");

        jScrollPane4.setBackground(new java.awt.Color(220, 229, 211));

        inventory_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Inventar"
            }
        ));
        jScrollPane4.setViewportView(inventory_table);

        javax.swing.GroupLayout inventory_panelLayout = new javax.swing.GroupLayout(inventory_panel);
        inventory_panel.setLayout(inventory_panelLayout);
        inventory_panelLayout.setHorizontalGroup(
            inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(inventory_panelLayout.createSequentialGroup()
                        .addComponent(filter_options_inventory)
                        .addGap(10, 10, 10)
                        .addComponent(searchfilter_inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(newdevice_button, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventory_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        inventory_panelLayout.setVerticalGroup(
            inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(inventory_title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(newdevice_button)
                .addGap(10, 10, 10)
                .addGroup(inventory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter_options_inventory)
                    .addComponent(searchfilter_inventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        layerpane.add(inventory_panel, "card5");

        return_panel.setBackground(new java.awt.Color(220, 229, 211));
        return_panel.setPreferredSize(new java.awt.Dimension(576, 840));

        re_notes.setColumns(20);
        re_notes.setRows(5);

        productname_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productname_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        productname_return.setText("Produktname");

        re_productname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        return_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        return_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        return_title.setText("Rückgabe");

        returndate.setForeground(new java.awt.Color(87, 121, 50));
        returndate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        yes.setBackground(new java.awt.Color(220, 229, 211));
        yes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yes.setText("Ja");

        re_manufacturer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        re_inventroyNumber.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        re_UserID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        manufacturer_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manufacturer_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        manufacturer_return.setText("Herstellerbezeichnung");

        userID_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userID_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userID_return.setText("Verliehen an");

        inventorynumber_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inventorynumber_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inventorynumber_return.setText("Inventarnummer");

        returnDate_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        returnDate_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        returnDate_return.setText("Rückgabedatum");

        notes_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        notes_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        notes_return.setText("Notizen");

        factorysettings_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        factorysettings_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        factorysettings_return.setText("Werkseinstellungen?");

        userName_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userName_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userName_return.setText("Name");

        userPhone_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userPhone_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userPhone_return.setText("Telefonnummer");

        userMail_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userMail_return.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userMail_return.setText("E-Mail");

        save_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        save_return.setText("Speichern");

        cancel_return.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancel_return.setText("Abbrechen");

        javax.swing.GroupLayout return_panelLayout = new javax.swing.GroupLayout(return_panel);
        return_panel.setLayout(return_panelLayout);
        return_panelLayout.setHorizontalGroup(
            return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(return_panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userMail_return, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(return_title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(return_panelLayout.createSequentialGroup()
                            .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productname_return, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manufacturer_return, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userID_return, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(returnDate_return, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(notes_return, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(factorysettings_return, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inventorynumber_return, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(userPhone_return, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(re_userPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(re_manufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(re_productname, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(re_inventroyNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(re_UserID, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(returndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(return_panelLayout.createSequentialGroup()
                                        .addComponent(save_return, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(cancel_return, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(re_userName, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                                .addComponent(re_userMail, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(re_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(userName_return, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        return_panelLayout.setVerticalGroup(
            return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(return_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(return_title, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re_productname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productname_return))
                .addGap(10, 10, 10)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re_manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturer_return))
                .addGap(10, 10, 10)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re_inventroyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inventorynumber_return))
                .addGap(10, 10, 10)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userID_return))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName_return)
                    .addComponent(re_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPhone_return)
                    .addComponent(re_userPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userMail_return)
                    .addComponent(re_userMail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returndate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDate_return))
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(return_panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(notes_return))
                    .addGroup(return_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(re_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yes)
                    .addComponent(factorysettings_return))
                .addGap(20, 20, 20)
                .addGroup(return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_return)
                    .addComponent(cancel_return))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        layerpane.add(return_panel, "card6");

        newdevice_panel.setBackground(new java.awt.Color(220, 229, 211));
        newdevice_panel.setPreferredSize(new java.awt.Dimension(576, 800));

        newdevice_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newdevice_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newdevice_title.setText("Neues Gerät");

        devicename_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        devicename_newdevice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        devicename_newdevice.setText("Gerätename");

        manufacturer_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manufacturer_newdevice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        manufacturer_newdevice.setText("Herstellerbezeichnung");

        inventorynumber_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inventorynumber_newdevice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inventorynumber_newdevice.setText("Inventarnummer");

        IMEInumber_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IMEInumber_newdevice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IMEInumber_newdevice.setText("IMEI Nummer");

        acquisitiondate_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acquisitiondate_newdevice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        acquisitiondate_newdevice.setText("Anschaffungsdatum");

        acquisitionDate.setForeground(new java.awt.Color(87, 121, 50));
        acquisitionDate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        save_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        save_newdevice.setText("Speichern");

        cancel_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cancel_newdevice.setText("Abbrechen");

        manufacturer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        productname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        inventoryNumber.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        imei.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        room_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        room_newdevice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        room_newdevice.setText("Raum");

        location.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        notes_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        notes_newdevice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        notes_newdevice.setText("Notizen");

        notes.setColumns(20);
        notes.setRows(5);
        jScrollPane2.setViewportView(notes);

        administrator_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        administrator_newdevice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        administrator_newdevice.setText("Administrator");

        administrator.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        administrator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        acquisitionvalue_newdevice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acquisitionvalue_newdevice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        acquisitionvalue_newdevice.setText("Anschaffungswert");

        acquisitionValue.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout newdevice_panelLayout = new javax.swing.GroupLayout(newdevice_panel);
        newdevice_panel.setLayout(newdevice_panelLayout);
        newdevice_panelLayout.setHorizontalGroup(
            newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newdevice_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newdevice_panelLayout.createSequentialGroup()
                        .addComponent(acquisitiondate_newdevice, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newdevice_panelLayout.createSequentialGroup()
                                .addComponent(save_newdevice, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(cancel_newdevice, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(acquisitionDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))
                    .addGroup(newdevice_panelLayout.createSequentialGroup()
                        .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(newdevice_title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newdevice_panelLayout.createSequentialGroup()
                                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(manufacturer_newdevice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(devicename_newdevice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inventorynumber_newdevice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(IMEInumber_newdevice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(room_newdevice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(notes_newdevice, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(administrator_newdevice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(acquisitionvalue_newdevice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(manufacturer)
                                    .addComponent(productname)
                                    .addComponent(inventoryNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .addComponent(imei, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addComponent(administrator, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(location)
                                    .addComponent(acquisitionValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))))
                        .addGap(0, 65, Short.MAX_VALUE))))
        );
        newdevice_panelLayout.setVerticalGroup(
            newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newdevice_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(newdevice_title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(devicename_newdevice)
                    .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturer_newdevice))
                .addGap(10, 10, 10)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inventorynumber_newdevice)
                    .addComponent(inventoryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IMEInumber_newdevice)
                    .addComponent(imei, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room_newdevice)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notes_newdevice)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(administrator, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(administrator_newdevice))
                .addGap(10, 10, 10)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acquisitionvalue_newdevice)
                    .addComponent(acquisitionValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acquisitiondate_newdevice)
                    .addComponent(acquisitionDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(newdevice_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_newdevice)
                    .addComponent(cancel_newdevice))
                .addGap(172, 172, 172))
        );

        layerpane.add(newdevice_panel, "card7");

        archive_panel.setBackground(new java.awt.Color(220, 229, 211));
        archive_panel.setPreferredSize(new java.awt.Dimension(576, 800));

        archive_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        archive_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        archive_title.setText("Archiv");

        searchfilter_archive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchfilter_archive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchfilter_archive.setToolTipText("Tabelle in der gefiltert/sortiert werden soll ");

        search_options_archive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        search_options_archive.setText("Filter- und Sortieroptionen");
        search_options_archive.setToolTipText("");

        filter_options_archive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filter_options_archive.setText("Filtern nach:");
        filter_options_archive.setToolTipText("");
        filter_options_archive.setMaximumSize(new java.awt.Dimension(90, 20));
        filter_options_archive.setMinimumSize(new java.awt.Dimension(90, 20));

        filterText_archive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filterText_archive.setToolTipText("Wert nach dem gefiltert werden soll");
        filterText_archive.setMaximumSize(new java.awt.Dimension(125, 30));
        filterText_archive.setMinimumSize(new java.awt.Dimension(70, 30));
        filterText_archive.setPreferredSize(new java.awt.Dimension(70, 30));

        asc_archive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        asc_archive.setText("ASC");
        asc_archive.setToolTipText("aufsteigende Sortierung");
        asc_archive.setAlignmentX(0.5F);
        asc_archive.setMaximumSize(new java.awt.Dimension(55, 30));
        asc_archive.setMinimumSize(new java.awt.Dimension(55, 30));
        asc_archive.setPreferredSize(new java.awt.Dimension(55, 30));

        desc_archive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        desc_archive.setText("DESC");
        desc_archive.setToolTipText("absteigende Sortierung");
        desc_archive.setMaximumSize(new java.awt.Dimension(60, 30));
        desc_archive.setMinimumSize(new java.awt.Dimension(60, 30));
        desc_archive.setPreferredSize(new java.awt.Dimension(60, 30));

        filterButton_archive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        filterButton_archive.setText("Filter anwenden");
        filterButton_archive.setPreferredSize(new java.awt.Dimension(125, 32));

        btClear_archive.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btClear_archive.setText("Clear");
        btClear_archive.setAlignmentX(0.2F);
        btClear_archive.setAlignmentY(0.2F);
        btClear_archive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btClear_archive.setIconTextGap(2);
        btClear_archive.setMaximumSize(new java.awt.Dimension(65, 30));
        btClear_archive.setMinimumSize(new java.awt.Dimension(65, 30));
        btClear_archive.setPreferredSize(new java.awt.Dimension(65, 30));
        btClear_archive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClear_archiveActionPerformed(evt);
            }
        });

        archive_ScrollPane.setBackground(new java.awt.Color(220, 229, 211));
        archive_ScrollPane.setRequestFocusEnabled(false);

        archive_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Archiv"
            }
        ));
        archive_table.setMinimumSize(new java.awt.Dimension(514, 64));
        archive_table.setPreferredSize(new java.awt.Dimension(514, 64));
        archive_ScrollPane.setViewportView(archive_table);

        javax.swing.GroupLayout archive_panelLayout = new javax.swing.GroupLayout(archive_panel);
        archive_panel.setLayout(archive_panelLayout);
        archive_panelLayout.setHorizontalGroup(
            archive_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archive_panelLayout.createSequentialGroup()
                .addGroup(archive_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(archive_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(archive_title, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                    .addGroup(archive_panelLayout.createSequentialGroup()
                        .addGroup(archive_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(archive_panelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(archive_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(search_options_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filter_options_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(archive_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchfilter_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filterText_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(archive_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(archive_panelLayout.createSequentialGroup()
                                        .addComponent(asc_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(desc_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(filterButton_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(btClear_archive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(archive_panelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(archive_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        archive_panelLayout.setVerticalGroup(
            archive_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archive_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(archive_title, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(archive_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_options_archive)
                    .addComponent(searchfilter_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asc_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(archive_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter_options_archive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterText_archive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton_archive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btClear_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(archive_ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        layerpane.add(archive_panel, "card4");

        scrollpane_startpage.setViewportView(layerpane);

        javax.swing.GroupLayout startpageLayout = new javax.swing.GroupLayout(startpage);
        startpage.setLayout(startpageLayout);
        startpageLayout.setHorizontalGroup(
            startpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpane_startpage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        startpageLayout.setVerticalGroup(
            startpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpane_startpage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );

        parentpanel.add(startpage, java.awt.BorderLayout.CENTER);

        getContentPane().add(parentpanel, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("jFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void newrentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newrentalActionPerformed
               
        layerpane.removeAll();
        layerpane.add(newrental_panel);
        layerpane.repaint();
        layerpane.revalidate();
        
        
        /**
        *
        * @author Katharina
        */
        Rental_Helper rh = new Rental_Helper(newrental_panel);
        rh.fillBoxes();
        rh.listenForSelectionAID();
        rh.listenForSelectionPN();
        rh.listenForSelectionM();
        rh.listenForSelectionIN();
        rh.listenForSelectionUID();
        rh.cancelButton();  
        rh.saveNewRental();
        
    }//GEN-LAST:event_newrentalActionPerformed

    private void rentallistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentallistActionPerformed
                
        layerpane.removeAll();
        layerpane.add(rentallist_panel);
        layerpane.repaint();
        layerpane.revalidate();
        
        
        /**
        *
        * @author Katharina
        */
        Rentallist_Helper rListHelper = new Rentallist_Helper (rentallist_table,
                    rental_ScrollPane, searchfilter_rentallist, asc_rentallist,
                    desc_rentallist, filterText_rentallist, 
                    filterbutton_rentallist, btClear_rentals, return_button );
        
        
        MyTableHelper.allRentals = null;
        rListHelper.populateTable();
        rListHelper.fillBox();
        rListHelper.filterTable();
        rListHelper.sortTable();
        rListHelper.clearSelection();
        rListHelper.newReturn(layerpane, return_panel);
    }//GEN-LAST:event_rentallistActionPerformed

    private void archiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archiveActionPerformed
        
        layerpane.removeAll();
        layerpane.add(archive_panel);
        layerpane.repaint();
        layerpane.revalidate();
        
        /**
        *
        * @author Katharina
        */
        ArchivHelper archHelper = new ArchivHelper(archive_table, archive_ScrollPane, 
                searchfilter_archive, asc_archive, desc_archive,
                filterText_archive, filterButton_archive, btClear_archive);
        
        MyTableHelper.rentalList = null;
        archHelper.populateTable();
        archHelper.fillBox();
        archHelper.sortTable();
        archHelper.filterTable();
        archHelper.clearSelection();
    }//GEN-LAST:event_archiveActionPerformed

    private void inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryActionPerformed
        
        layerpane.removeAll();
        layerpane.add(inventory_panel);
        layerpane.repaint();
        layerpane.revalidate();
        
    }//GEN-LAST:event_inventoryActionPerformed

    
    private void re_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re_userActionPerformed

    private void re_rentaldateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_rentaldateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re_rentaldateActionPerformed

    private void re_administratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_administratorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re_administratorActionPerformed

    private void re_inventorynumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_inventorynumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_re_inventorynumberActionPerformed

   
    
    /**
    *
    * @author Katharina
    */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        hp.closeDB();
        System.out.println("Connection to Database closed");
    }//GEN-LAST:event_formWindowClosing

    private void return_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_buttonActionPerformed
        
        /*
        DefaultTableModel model = (DefaultTableModel) rentallist_table.getModel();

        int index = rentallist_table.getSelectedRow();

        String ret_productname = model.getValueAt(index, 2).toString();
        String ret_manufacturer = model.getValueAt(index, 3).toString();
        String ret_user = model.getValueAt(index, 4).toString();
        String ret_inventorynumber = model.getValueAt(index, 1).toString();

        re_productname.setText(ret_productname);
        re_manufacturer.setText(ret_manufacturer);
        re_inventroyNumber.setText(ret_user);
        re_UserID.setText(ret_inventorynumber);

        re_productname.setEditable(false);
        re_manufacturer.setEditable(false);
        re_inventroyNumber.setEditable(false);
        re_UserID.setEditable(false);

        layerpane.removeAll();
        layerpane.add(return_panel);
        layerpane.repaint();
        layerpane.revalidate();
        */
        
    }//GEN-LAST:event_return_buttonActionPerformed

    private void btClear_archiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClear_archiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btClear_archiveActionPerformed

    public JPanel getReturn_panel() {
        return return_panel;
    }
    
    public JLayeredPane getLayerpane() {
        return layerpane;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMEInumber_newdevice;
    private com.raven.datechooser.DateChooser acquisitionDate;
    private javax.swing.JTextField acquisitionValue;
    private javax.swing.JLabel acquisitiondate_newdevice;
    private javax.swing.JLabel acquisitionvalue_newdevice;
    private javax.swing.JTextField adminFullName;
    private javax.swing.JComboBox<String> administrator;
    private javax.swing.JLabel administrator_newdevice;
    private javax.swing.JComboBox<String> administrator_newrental;
    private javax.swing.JButton archive;
    private javax.swing.JScrollPane archive_ScrollPane;
    private javax.swing.JPanel archive_panel;
    private javax.swing.JTable archive_table;
    private javax.swing.JLabel archive_title;
    private javax.swing.JRadioButton asc_archive;
    private javax.swing.JRadioButton asc_rentallist;
    private javax.swing.JButton btClear_archive;
    private javax.swing.JButton btClear_rentals;
    private javax.swing.JToggleButton cancel_newdevice;
    private javax.swing.JButton cancel_newrental;
    private javax.swing.JButton cancel_return;
    private javax.swing.JLabel date;
    private javax.swing.JRadioButton desc_archive;
    private javax.swing.JRadioButton desc_rentallist;
    private javax.swing.JLabel devicename;
    private javax.swing.JLabel devicename_newdevice;
    private javax.swing.JLabel factorysettings_return;
    private javax.swing.JButton filterButton_archive;
    private javax.swing.JLabel filterString_rentallist;
    private javax.swing.JTextField filterText_archive;
    private javax.swing.JTextField filterText_rentallist;
    private javax.swing.JLabel filter_options_archive;
    private javax.swing.JLabel filter_options_inventory;
    private javax.swing.JLabel filter_options_rentallist;
    private javax.swing.JButton filterbutton_rentallist;
    private javax.swing.JPanel home_panel;
    private javax.swing.JTextField imei;
    private javax.swing.JButton inventory;
    private javax.swing.JTextField inventoryNumber;
    private javax.swing.JLabel inventory_number;
    private javax.swing.JPanel inventory_panel;
    private javax.swing.JTable inventory_table;
    private javax.swing.JLabel inventory_title;
    private javax.swing.JLabel inventorynumber_newdevice;
    private javax.swing.JComboBox<String> inventorynumber_newrental;
    private javax.swing.JLabel inventorynumber_return;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLayeredPane layerpane;
    private javax.swing.JTextField location;
    private javax.swing.JTextField manufacturer;
    private javax.swing.JLabel manufacturer_newdevice;
    private javax.swing.JComboBox<String> manufacturer_newrental;
    private javax.swing.JLabel manufacturer_return;
    private javax.swing.JLabel manufacturername;
    private javax.swing.JButton newdevice_button;
    private javax.swing.JPanel newdevice_panel;
    private javax.swing.JLabel newdevice_title;
    private javax.swing.JButton newrental;
    private javax.swing.JPanel newrental_panel;
    private javax.swing.JLabel newrentaltitle;
    private javax.swing.JTextArea notes;
    private javax.swing.JLabel notes_newdevice;
    private javax.swing.JLabel notes_return;
    private javax.swing.JPanel parentpanel;
    private javax.swing.JTextField productname;
    private javax.swing.JComboBox<String> productname_newrental;
    private javax.swing.JLabel productname_return;
    private javax.swing.JTextField re_UserID;
    private javax.swing.JTextField re_inventroyNumber;
    private javax.swing.JTextField re_manufacturer;
    private javax.swing.JTextArea re_notes;
    private javax.swing.JTextField re_productname;
    private javax.swing.JTextField re_userMail;
    private javax.swing.JTextField re_userName;
    private javax.swing.JTextField re_userPhone;
    private javax.swing.JLabel rentTo;
    private com.raven.datechooser.DateChooser rentalDate_newrental;
    private javax.swing.JScrollPane rental_ScrollPane;
    private javax.swing.JButton rentallist;
    private javax.swing.JPanel rentallist_panel;
    private javax.swing.JTable rentallist_table;
    private javax.swing.JLabel rentallist_title;
    private javax.swing.JLabel rentedby;
    private javax.swing.JLabel returnDate_return;
    private javax.swing.JButton return_button;
    private javax.swing.JPanel return_panel;
    private javax.swing.JLabel return_title;
    private com.raven.datechooser.DateChooser returndate;
    private javax.swing.JLabel room_newdevice;
    private javax.swing.JToggleButton save_newdevice;
    private javax.swing.JButton save_newrental;
    private javax.swing.JButton save_return;
    private javax.swing.JScrollPane scrollpane_startpage;
    private javax.swing.JLabel search_options_archive;
    private javax.swing.JComboBox<String> searchfilter_archive;
    private javax.swing.JComboBox<String> searchfilter_inventory;
    private javax.swing.JComboBox<String> searchfilter_rentallist;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel startpage;
    private javax.swing.JPanel toppenal;
    private javax.swing.JTextField userEmail;
    private javax.swing.JTextField userFirstName;
    private javax.swing.JComboBox<String> userID_newrental;
    private javax.swing.JLabel userID_return;
    private javax.swing.JTextField userLastName;
    private javax.swing.JLabel userMail_return;
    private javax.swing.JLabel userName_return;
    private javax.swing.JTextField userPhone;
    private javax.swing.JLabel userPhone_return;
    private javax.swing.JComboBox<String> year_newrental;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables

    
    /**
    *
    * @author Katharina
    */
    @Override
    public void run() {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        new GUI().setVisible(true);
    }
}
